#!/usr/bin/env bash

# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"
else
  printf "ERROR: An RVM installation was not found.\n"
fi

set -e

function run {
  gem list --local bundler | grep bundler || gem install bundler --no-ri --no-rdoc

  for v in 2.3.2 2.3.5 2.3.11 3.0.10 3.1.0 "" edge ; do
      echo "Running bundle exec rspec spec against activesupport / activerecord ${v}..."
      ACTIVE_HASH_ACTIVERECORD_VERSION=${v} bundle update --local activerecord || ACTIVE_HASH_ACTIVERECORD_VERSION=${v} bundle update activerecord
      bundle exec rspec spec
  done
}

rvm use ruby-1.8.7@active_hash --create
run

rvm use ree-1.8.7@active_hash --create
run

rvm use ruby-1.9.2@active_hash --create
run

echo 'Success!'
