#!/usr/bin/env bash

# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
    source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
    source "/usr/local/rvm/scripts/rvm"
else
    echo "ERROR: An RVM installation was not found.\n"
fi

set -o errexit

for v in ruby-1.8.7 ree-1.8.7 ruby-1.9.2 ruby-1.9.3 ; do
    rvm use ${v}@active_hash --create
    bundle install --local || bundle install
    rake appraisal:install
    rake appraisal spec
done

echo 'Success!'
